### ISSUE TITLE
"Help" flag to list flags

### ISSUE THREAD

**Issue by matiux** [ogier/pflag#34]
Hi,
is there a way to don't lose the -h flag that in the standard library produce a list of all flags registered?

Hi have register a flag:
```
var userID *int = pflag.IntP("user", "u", 0, "User ID")

flag.Parse()

fmt.Printf("User ID %v\n", *userID)
```

if I run `go run main.go -h` I get this message:

```
Usage of /tmp/go-build252835213/command-line-arguments/_obj/exe/main:
exit status 2
```

Thanks

**Comment by matiux** [comment]
Ops, I have solved by me. I was wrong the `pflag.Parse()` syntax

**Comment by ogier** [comment]
Glad you were able to solve the issue!
