### ISSUE TITLE
Parsing ranges apart from single values

### ISSUE THREAD

**Issue by Gituser143** [ogier/pflag#37]
Is there any functionality to parse ranges as flags. For example the namp tool takes a range of ports to scan `nmap HOST -p 10-100` 

This would scan ports in the range 10 to 100. Similar functionalities being implemented would be helpful!

**Comment by Gituser143** [comment]
A very naive approach I have in mind for the same is as follows:
```go
func ParseRange(Range string) (int, int) {
	if strings.Contains(Range, "-") {
		Vals := strings.Split(Range, "-")

		if len(Vals) != 2 {
			log.Fatal("Failed while parsing ranges. Invalid port range format!")
		}

		var min, max int

		if strings.Compare(Vals[0], "") == 0 {
			min = 1
		} else {
			val, err := strconv.Atoi(Vals[0])
			if err != nil {
				fmt.Println("Failed to parse ranges!")
				log.Fatal(err)
			}
			min = val
		}

		if strings.Compare(Vals[1], "") == 0 {
			max = 65535
		} else {
			val, err := strconv.Atoi(Vals[1])
			if err != nil {
				fmt.Println("Failed to parse ranges!")
				log.Fatal(err)
			}
			max = val
		}

		return min, max

	} else {
		val, err := strconv.Atoi(portRange)
		if err != nil {
			fmt.Println("Failed to parse values!")
			log.Fatal(err)
		}

		return val, nil

	}
}
```

Here, we could take in a string value as a flag and parse it separately based on whether or not a `-` is present. Default values can be provided if in case vales on either side of the `-` are omitted. In my above example default values are 1, 65535 (For ports). 

We return the minimum value of the range and maximum through the above function and this can be used as ranges to iterate over. If in case a single value is given instead of range, we simply give just that value and nil.

**Comment by ogier** [comment]
This package tries to stick to what's available in the https://golang.org/pkg/flag/ package. You can use the `VarP` function to define a flag like this in your code that satisfies the `Value` interface. If you think this is a generally useful type of flag, the https://github.com/spf13/pflag fork has a bunch of extra flag types defined and takes a more "batteries-included" approach to adding new flags, so perhaps you could try contributing it there.
